/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package morty.Vustas;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import Config.UpdateDatos;
import Config.Conexion;
import Config.DeleteDatos;
import Config.InsertarDatos;
import java.sql.*;
/**
 *
 * @author ricardo
 */
public class crearPlataformas extends javax.swing.JInternalFrame {

    /**
     * Creates new form crearPlataformas
     */
    public crearPlataformas() {
        initComponents();
        listarServicios();
    }

    public void limpiarCampos(){
        entryNombre.setText("");
        entryDescripcion.setText("");
        entryPrecio.setText("");
        
    }
    
    public void listarServicios() {
    	Conexion conexion = new Conexion();
    	Connection cn = conexion.getConnection();
    	
    	if(cn != null) {
    		PreparedStatement st;
    		ResultSet resultado;
    		
    		String sql = "SELECT idPlataformas, nombre, descripcion, precio FROM serviciosplataforma";
    		
    		try {
				DefaultTableModel modelo;
				st = cn.prepareStatement(sql);
				
				resultado = st.executeQuery(); //ejecutamos la consulta y obtenemos los datos
				
				Object[] servicios = new Object[4];
                                modelo = (DefaultTableModel)tablaPlataformas.getModel();
                                modelo.setRowCount(0);
				while(resultado.next()) {
					servicios[0] = resultado.getInt("idPlataformas");
					servicios[1] = resultado.getString("nombre");
					servicios[2] = resultado.getString("descripcion");
					servicios[3] = resultado.getString("precio");
					
					modelo.addRow(servicios);
				}
				tablaPlataformas.setModel(modelo);
				
			} catch (SQLException e) {
				JOptionPane.showMessageDialog(null, "Error al listar los servicios: "+ e, "SpiderNET", JOptionPane.ERROR_MESSAGE);
				// TODO: handle exception
			}
                
    	}
    	
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        entryID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        entryNombre = new javax.swing.JTextField();
        entryDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        entryPrecio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPlataformas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Plataformas - Servicios");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Servicios"));

        jLabel1.setText("ID");

        entryID.setEditable(false);

        jLabel2.setText("Nombre");

        jLabel3.setText("Descripcion");

        jLabel4.setText("Precio");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha-de-circulo-de-disquete-a-la-derecha.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/girar-cuadrado.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/marca-x-rectangular.png"))); // NOI18N
        jButton7.setText("Eliminar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entryID, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(entryPrecio))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entryNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entryDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(entryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(entryNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(entryDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(entryPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(btnActualizar)
                    .addComponent(jButton7))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tablaPlataformas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Precio"
            }
        ));
        tablaPlataformas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPlataformasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPlataformas);
        if (tablaPlataformas.getColumnModel().getColumnCount() > 0) {
            tablaPlataformas.getColumnModel().getColumn(0).setMinWidth(30);
            tablaPlataformas.getColumnModel().getColumn(0).setPreferredWidth(30);
            tablaPlataformas.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = entryNombre.getText();
        if(nombre.length() > 0){
            String descripcion = entryDescripcion.getText();
            String precio = entryPrecio.getText();
            InsertarDatos insertarDatos = new InsertarDatos();
            insertarDatos.insertarPlataformas(nombre, descripcion, precio);
            limpiarCampos();
            listarServicios();
        }else{
            JOptionPane.showMessageDialog(null, "No podemos registrar un servicio sin nombre", "SpiderNET", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String nombre = entryNombre.getText();
        
        if(nombre.length() > 0){
            int id = Integer.parseInt(entryID.getText());
            String descripcion = entryDescripcion.getText();
            String precio = entryPrecio.getText();
            
            UpdateDatos datos = new UpdateDatos();
            datos.actualizarServicios(id, nombre, descripcion, precio);
            limpiarCampos();
            listarServicios();
        }else{
            JOptionPane.showMessageDialog(null, "No podemos actualizar un equipo sin nombre", "SpiderNET", JOptionPane.WARNING_MESSAGE);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int filaSeleccionada;
        filaSeleccionada = tablaPlataformas.getSelectedRow();
        
        if(filaSeleccionada >= 0){
            //eliminar
            int id = Integer.parseInt(entryID.getText());
            DeleteDatos deleteDatos = new DeleteDatos();
            deleteDatos.eliminarServicio(id);
            listarServicios();;
            limpiarCampos();
        }else{
            JOptionPane.showMessageDialog(null, "Para eliminar, primero selecciona un elemento", "SpiderNET", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tablaPlataformasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPlataformasMouseClicked
        int filaSeleccionada;
        
        filaSeleccionada = tablaPlataformas.getSelectedRow();
        
        if(filaSeleccionada >= 0){
            entryID.setText(String.valueOf(tablaPlataformas.getValueAt(filaSeleccionada, 0)));
            entryNombre.setText(String.valueOf(tablaPlataformas.getValueAt(filaSeleccionada, 1)));
            entryDescripcion.setText(String.valueOf(tablaPlataformas.getValueAt(filaSeleccionada, 2)));
            entryPrecio.setText(String.valueOf(tablaPlataformas.getValueAt(filaSeleccionada, 3)));
        }else{
            JOptionPane.showMessageDialog(null, "Primero selecciona un elemento");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaPlataformasMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JTextField entryDescripcion;
    private javax.swing.JTextField entryID;
    private javax.swing.JTextField entryNombre;
    private javax.swing.JTextField entryPrecio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPlataformas;
    // End of variables declaration//GEN-END:variables
}
